apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ag-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: ceph
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
