apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-mon
spec:
  template:
    metadata:
      labels:
        app: ceph-mon
    spec:
      nodeSelector: 
        ceph-mon: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      initContainers:
      - name: ceph-init-mon-keyring
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - "-c"
        - |
          set -ex
          #mkdir -p /var/lib/ceph/bootstrap-osd
          #mkdir -p /var/lib/ceph/bootstrap-mds
          cp -vf /etc/ceph/ceph.mon.keyring.seed /etc/ceph/ceph.mon.keyring
          #cp -vf /tmp/ceph/ceph.client.admin.keyring /etc/ceph/ceph.client.admin.keyring
          #cp -vf /tmp/ceph/bootstrap-osd/ceph.keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
          #cp -vf /tmp/ceph/bootstrap-mds/ceph.keyring /var/lib/ceph/bootstrap-mds/ceph.keyring
        volumeMounts:
        - name: ceph-conf
          mountPath: /etc/ceph/ceph.mon.keyring.seed
          subPath: ceph.mon.keyring
          readOnly: true
        - name: etc-ceph 
          mountPath: /etc/ceph
          readOnly: false
      containers:
      - name: ceph-mon
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
        env:
        - name: CEPH_DAEMON
          value: mon
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #- name: K8S_HOST_NETWORK
        #  value: "1"
        - name: CEPH_PUBLIC_NETWORK
          value: 172.16.0.0/20
        - name: K8S_MON_SELECTOR 
          value: app=ceph-mon
        ports:
        - containerPort: 6789
        #livenessProbe:
        #  tcpSocket:
        #    port: 6789
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 6789                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: etc-ceph 
          mountPath: /etc/ceph
          readOnly: false
        - name: ceph-conf 
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
          readOnly: false
        - name: ceph-conf 
          mountPath: /etc/ceph/ceph.client.admin.keyring
          subPath: ceph.client.admin.keyring
          readOnly: false
        - name: lib 
          mountPath: /var/lib/ceph
          readOnly: false
        - name: logs 
          mountPath: /var/log/ceph
          readOnly: false
      volumes:
      - name: etc-ceph
        emptyDir: {}
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: lib
        hostPath:
          path: /data/ceph/lib
      - name: logs
        hostPath:
          path: /data/ceph/log
      - name: ceph-conf
        configMap:
          name: ceph-conf
          defaultMode: 0777
