apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-mon
spec:
  template:
    metadata:
      labels:
        app: ceph-mon
    spec:
      nodeSelector: 
        ceph-mon: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      initContainers:
      - name: ceph-init-mon-keyring
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - "-c"
        - |
          set -ex
          mkdir -p /var/lib/ceph/bootstrap-osd
          mkdir -p /var/lib/ceph/bootstrap-mds
          cp -vf /tmp/ceph/etc/* /etc/ceph/
          cp -vf /tmp/ceph/bootstrap-osd/ceph.keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
          cp -vf /tmp/ceph/bootstrap-mds/ceph.keyring /var/lib/ceph/bootstrap-mds/ceph.keyring
        volumeMounts:
        - name: ceph-conf
          mountPath: /tmp/ceph/etc 
          readOnly: true
        - name: bootstrap-osd-keyring 
          mountPath: /tmp/ceph/bootstrap-osd/ceph.keyring
          subPath: ceph.keyring
          readOnly: false
        - name: bootstrap-mds-keyring 
          mountPath: /tmp/ceph/bootstrap-mds/ceph.keyring
          subPath: ceph.keyring
          readOnly: false
        - name: etc-ceph 
          mountPath: /etc/ceph
          readOnly: false
        - name: lib 
          mountPath: /var/lib/ceph
          readOnly: false
      containers:
      - name: ceph-mon
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        #command:
        #- sleep
        #- "3600"
        env:
        - name: CEPH_DAEMON
          value: mon
        - name: MON_IP
          value: 172.16.0.10,172.16.0.15,172.16.0.16
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.podIP
        #- name: K8S_HOST_NETWORK
        #  value: "1"
        - name: CEPH_PUBLIC_NETWORK
          value: 172.16.0.0/20
        #- name: K8S_MON_SELECTOR 
        #  value: app=ceph-mon
        ports:
        - containerPort: 6789
        #livenessProbe:
        #  tcpSocket:
        #    port: 6789
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 6789                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: etc-ceph 
          mountPath: /etc/ceph
          readOnly: false
        - name: lib 
          mountPath: /var/lib/ceph
          readOnly: false
        - name: logs 
          mountPath: /var/log/ceph
          readOnly: false
      volumes:
      - name: etc-ceph
        hostPath:
          path: /data/ceph/etc
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: lib
        hostPath:
          path: /data/ceph/lib
      - name: logs
        hostPath:
          path: /data/ceph/log
      - name: ceph-conf
        configMap:
          name: ceph-conf
          defaultMode: 0777
      - name: bootstrap-osd-keyring
        configMap:
          name: bootstrap-osd-keyring
          defaultMode: 0777
      - name: bootstrap-mds-keyring
        configMap:
          name: bootstrap-mds-keyring
          defaultMode: 0777
