apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: gremlin
  name: gremlin
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      qcloud-app: gremlin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        qcloud-app: gremlin
    spec:
      containers:
      - name: skg-gremlin
        image: ccr.ccs.tencentyun.com/aisec/skg_gremlin:v0.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/testdata
          name: vol
        livenessProbe:
          tcpSocket:
            port: 8182
          initialDelaySeconds: 10                                                                    
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8182                                                                               
          initialDelaySeconds: 10                                                                    
          periodSeconds: 5
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      volumes:
      - hostPath:
          path: /mnt
        name: vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: gremlin
  name: gremlin
  namespace: default
spec:
  ports:
  - name: tcp-8182-8182-n6chr
    port: 8182
    protocol: TCP
    targetPort: 8182
  selector:
    qcloud-app: gremlin
  type: LoadBalancer
