apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: gremlin
  name: gremlin
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: gremlin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        qcloud-app: gremlin
    spec:
      containers:
      - name: skg-gremlin
        image: ccr.ccs.tencentyun.com/aisec/skg_gremlin:v0.6
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: 
        - "-c"
        - "mkdir /mnt/cephfs; ceph-fuse /mnt/cephfs -n client.admin; sleep infinity"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: true
        ports:
        - containerPort: 8182
        volumeMounts:
        - name: ceph-conf
          mountPath: /etc/ceph/ 
          readOnly: true
        #livenessProbe:
        #  tcpSocket:
        #    port: 8182
        #  initialDelaySeconds: 10                                                                    
        #  periodSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 8182                                                                               
        #  initialDelaySeconds: 10                                                                    
        #  periodSeconds: 5
      #dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      volumes:
      - name: ceph-conf
        configMap:
          name: ceph-conf-combined
          defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: gremlin
  name: gremlin
  namespace: default
spec:
  ports:
  - name: tcp-8182-8182-n6chr
    port: 8182
    protocol: TCP
    targetPort: 8182
  selector:
    qcloud-app: gremlin
  type: LoadBalancer
