apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: ceph-mon
  clusterIP: None  
