apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: ceph
    daemon: osd-zap
  name: ceph-osd-zap
  namespace: ceph
spec:
  template:
    metadata:
      name: ceph-osd-zap
      namespace: ceph
      labels:
        app: ceph
        daemon: osd-zap
    spec:
      nodeSelector: 
        ceph-osd: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      initContainers:
      - name: ceph-zap-device
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: CEPH_DAEMON
          value: zap_device
        - name: OSD_DEVICE
          value: /dev/vdb
        volumeMounts:
        - name: dev
          mountPath: /dev
      containers:
      - name: ceph-zap-device-over
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - sleep 
        - "3600"
      volumes:
        - name: dev
          hostPath:
            path: /dev
