apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: ceph
    daemon: mgr
  name: ceph-mgr
  namespace: ceph
spec:
  template:
    metadata:
      name: ceph-mgr
      namespace: ceph
      labels:
        app: ceph
        daemon: mgr
    spec:
      nodeSelector: 
        node-type: storage
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      containers:
      - name: ceph-mgr
        image: ceph/daemon:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        #command:
        #- sleep
        #- "3600"
        env:
        - name: CEPH_DAEMON
          value: mgr
        ports:
        - containerPort: 7000
        #livenessProbe:
        #  tcpSocket:
        #    port: 6800
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 6800                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
        - name: ceph-bootstrap-osd-keyring
          mountPath: /var/lib/ceph/bootstrap-osd
        - name: ceph-bootstrap-mds-keyring
          mountPath: /var/lib/bootstrap-mds
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: ceph-conf
          mountPath: /etc/ceph
        #- name: lib 
        #  mountPath: /var/lib/ceph
        #- name: logs 
        #  mountPath: /var/log/ceph
        #  readOnly: false
      volumes:
        - name: ceph-conf
          configMap:
            name: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          configMap:
            name: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          configMap:
            name: ceph-bootstrap-mds-keyring
        - name: localtime
          hostPath:
            path: /etc/localtime
        #- name: etc-ceph
        #  emptyDir: {}
        #- name: lib
        #  emptyDir: {}
