apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-osd
  namespace: ceph
spec:
  template:
    metadata:
      name: ceph-osd
      namespace: ceph
      labels:
        app: ceph
        daemon: osd
    spec:
      nodeSelector: 
        node-type: storage
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      initContainers:
      - name: ceph-zap-device
        image: ceph/daemon:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: CEPH_DAEMON
          value: zap_device
        - name: OSD_DEVICE
          value: /dev/vdb
        volumeMounts:
        - name: dev
          mountPath: /dev
      containers:
      - name: ceph-osd
        image: ceph/daemon:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        #command:
        #- sleep
        #- "3600"
        env:
        - name: CEPH_DAEMON
          value: osd
        - name: OSD_DEVICE
          value: /dev/vdb
        - name: OSD_TYPE
          value: disk
        - name: OSD_BLUESTORE
          value: "1"
        ports:
        - containerPort: 6800
        #livenessProbe:
        #  tcpSocket:
        #    port: 6800
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 6800                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
        - name: ceph-bootstrap-osd-keyring
          mountPath: /var/lib/ceph/bootstrap-osd
        - name: ceph-bootstrap-mds-keyring
          mountPath: /var/lib/bootstrap-mds
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: ceph-conf
          mountPath: /etc/ceph
        #- name: lib 
        #  mountPath: /var/lib/ceph
        #- name: logs 
        #  mountPath: /var/log/ceph
        #  readOnly: false
        - name: dev
          mountPath: /dev
      volumes:
        - name: ceph-conf
          configMap:
            name: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          configMap:
            name: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          configMap:
            name: ceph-bootstrap-mds-keyring
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: dev
          hostPath:
            path: /dev
        #- name: etc-ceph
        #  emptyDir: {}
        #- name: lib
        #  emptyDir: {}
