apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: ceph
    daemon: mgr
  name: ceph-mgr
  namespace: ceph
spec:
  template:
    metadata:
      name: ceph-mgr
      namespace: ceph
      labels:
        app: ceph
        daemon: mgr
    spec:
      nodeSelector: 
        ceph-mgr: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      containers:
      - name: ceph-mgr
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        #command:
        #- sleep
        #- "3600"
        env:
        - name: CEPH_DAEMON
          value: mgr
        #ports:
        #- containerPort: 7000
        #livenessProbe:
        #  tcpSocket:
        #    port: 7000
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 7000                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
          - name: etc-ceph 
            mountPath: /etc/ceph
            readOnly: false
          - name: lib 
            mountPath: /var/lib/ceph
            readOnly: false
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: etc-ceph
          hostPath:
            path: /data/ceph/etc
        - name: lib
          hostPath:
            path: /data/ceph/lib
        - name: localtime
          hostPath:
            path: /etc/localtime
