apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceph-mds
  namespace: ceph
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ceph
        daemon: mds
      namespace: ceph
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      containers:
      - name: ceph-mds
        image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        #command:
        #- sleep
        #- "3600"
        env:
        - name: CEPH_DAEMON
          value: mds
        - name: CEPHFS_CREATE
          value: "0"
        #ports:
        #- containerPort: 6900
        #livenessProbe:
        #  tcpSocket:
        #    port: 6900
        #  initialDelaySeconds: 60                                                                    
        #  timeoutSeconds: 5
        #readinessProbe:
        #  tcpSocket:
        #    port: 6900                                                                               
        #  timeoutSeconds: 5
        volumeMounts:
          - name: etc-ceph 
            mountPath: /etc/ceph
            readOnly: false
          - name: lib 
            mountPath: /var/lib/ceph
            readOnly: false
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: etc-ceph
          hostPath:
            path: /data/ceph/etc
        - name: lib
          hostPath:
            path: /data/ceph/lib
        - name: localtime
          hostPath:
            path: /etc/localtime
